import { expect, test } from '@playwright/test'

test('AC1 AC2 AC20-AC26: Cmd/Ctrl+P finds nested workspace files and preserves preview/pin activation', async ({ page }) => {
  await page.goto('/?fixture=finder-workspace')
  await page.keyboard.press('Control+p')
  const finder = page.getByRole('dialog', { name: 'Go to File' })
  await expect(finder).toBeVisible()
  await finder.getByRole('searchbox').fill('nested guide')
  await expect(finder.getByRole('option', { name: /Guide\.md/ })).toBeVisible()
  await page.keyboard.press('Enter')
  await expect(page.getByTestId('document-tab')).toHaveAttribute('aria-description', /Preview/)
  await expect(page.getByTestId('document-tab')).toBeFocused()
  await page.keyboard.press('Control+p')
  await finder.getByRole('searchbox').fill('nested guide')
  await page.keyboard.press('Control+Enter')
  await page.keyboard.press('Control+p')
  await finder.getByRole('searchbox').fill('data.csv')
  await page.keyboard.press('Control+Enter')
  await expect(page.getByTestId('document-tab').filter({ hasText: 'data' })).not.toHaveAttribute('aria-description', /Preview/)

  await page.keyboard.press('Control+p')
  await expect(finder).toBeVisible()
  await page.keyboard.down('Control')
  await page.keyboard.press('Tab')
  await expect(finder).toBeHidden()
  await expect(page.getByRole('dialog', { name: 'Switch Tab' })).toBeVisible()
  await page.keyboard.press('p')
  await expect(page.getByRole('dialog', { name: 'Switch Tab' })).toBeHidden()
  await expect(finder).toBeVisible()
  await page.keyboard.up('Control')
  await page.keyboard.press('Escape')
  await page.keyboard.press(process.platform === 'darwin' ? 'Meta+,' : 'Control+,')
  await expect(page.getByTestId('settings-dialog')).toBeVisible()
  await page.keyboard.press('Control+p')
  await page.keyboard.press('Control+Tab')
  await expect(finder).toBeHidden()
  await expect(page.getByRole('dialog', { name: 'Switch Tab' })).toBeHidden()
})

test('AC27-AC36: Ctrl+Tab presents MRU tab state and switches without losing dirty or preview state', async ({ page }) => {
  await page.goto('/?fixture=finder-tabs')
  await page.keyboard.down('Control')
  await page.keyboard.press('Tab')
  const switcher = page.getByRole('dialog', { name: 'Switch Tab' })
  await expect(switcher).toBeVisible()
  await expect(switcher.getByRole('option')).toHaveCount(3)
  await page.keyboard.press('Tab')
  await page.keyboard.up('Control')
  await expect(switcher).toBeHidden()
  await expect(page.getByTestId('document-tab').filter({ hasText: 'three' })).toHaveAttribute('aria-selected', 'true')
})
