export const channels = {
  bootstrap: 'markzen:bootstrap',
  documentClose: 'markzen:document:close',
  documentConfirmClose: 'markzen:document:confirm-close',
  documentConfirmWindowClose: 'markzen:document:confirm-window-close',
  documentAcceptExternal: 'markzen:document:accept-external',
  documentCommand: 'markzen:document:command',
  documentExternal: 'markzen:document:external',
  documentCreateTab: 'markzen:document:create-tab',
  documentOpen: 'markzen:document:open',
  documentOverwriteExternal: 'markzen:document:overwrite-external',
  documentQuitSaveAllComplete: 'markzen:document:quit-save-all-complete',
  documentRetryCleanup: 'markzen:document:retry-cleanup',
  documentSave: 'markzen:document:save',
  documentSaveAndRename: 'markzen:document:save-and-rename',
  documentSaveAs: 'markzen:document:save-as',
  documentUpdateMenuState: 'markzen:document:update-menu-state',
  windowClose: 'markzen:window:close',
  windowGetState: 'markzen:window:get-state',
  windowMinimize: 'markzen:window:minimize',
  windowState: 'markzen:window:state',
  windowToggleMaximize: 'markzen:window:toggle-maximize',
} as const
